#!/usr/bin/env python2
#
# Copyright (C) 2016
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

# Based on Ganeti EXtStorageProviders code (https://code.grnet.gr/projects/extstorage)

"""Grow Volume inside a Dell Equallogic 

following variables should be present:
 - VOL_NAME        : The UUID of the new Image file
 - VOL_SIZE        : The size of the new Image (in megabytes)
 - VOL_NEW_SIZE    : The new size of the Image (in megabytes)
 
Return O after successfull connect, 1 on failure
"""

import sys
from common import config
from common import env
from common import eql

if __name__ == '__main__':
    conf = config.config()
    enviroment = env.env()
    eql01 = eql.eql(conf.device_hostname, conf.management_ip, conf.management_user, conf.management_password)
    
    eql01.connect() 
    data = eql01.volGrow(enviroment.get('VOL_NAME'), enviroment.get('VOL_NEW_SIZE'))
    eql01.close()

    sys.exit(0)